- frontend/src/App.vue
- frontend/src/components/CostTable.vue
- frontend/src/components/CostTableMenu.vue
> feat(frontend): allow user to specify the min number of VCPU and RAM

- client/aws/aws.go
- client/client.go
We now focus on MySQL and POSTGRES.
> hide engine type ORACLE & SQLSERVER

- frontend/src/App.vue
- frontend/src/components/CostTable.vue
- frontend/src/components/CostTableMenu.vue
> feat(frontend): allow use to select mutiple engine

- frontend/src/App.vue
- frontend/src/components/CostTable.vue
- frontend/src/components/CostTableMenu.vue
> feat(frontend): Muti charge type

- frontend/src/App.vue
- frontend/src/components/CostTableMenu.vue
- frontend/src/components/CostTableRegionMenu.vue
> extract region menu from menu

- frontend/src/layout/AppLayout.vue
- frontend/src/router/index.ts
- frontend/src/types/common/common.ts
- frontend/src/types/searchConfig.ts
- frontend/src/types/term.ts
The params in the URL will be in the form of: `/?cloudProvider=AWS&region=US+East+(N.+Virginia),US+West+(Oregon)&engineType=MYSQL&chargeType=OnDemand&minCPU=0&minRAM=0&keyword=`
> sync URL param and store

- frontend/src/components/CostTableMenu.vue
- frontend/src/components/CostTableRegionMenu.vue
- frontend/src/layout/AppLayout.vue
> Use props for rendering the search config value & remove useless code

- frontend/src/components/CostTable.vue
> condense the title of the data table

- frontend/src/components/CostTable.vue
> refine the processor span

- frontend/src/components/CostTable.vue
> add provider's icon to the instance name col

- frontend/src/components/TheFooter.vue
> add star history to the footer

- README.md
- client/aws/aws.go
- client/client.go
- client/gcp/gcp.go
- client/gcp/gcp_test.go
- frontend/src/views/AppView.vue
- main/main.go
- start.sh
- store/data/sample.json
- store/db_instance.go
- store/db_instance_test.go
Added a main function for seeding data and a script for preparing our service on render.
> use script to seed data

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/ApexChart/CostLineChart.vue
- frontend/src/components/ApexChart/types/index.ts
- frontend/src/components/ApexChart/utils/addFilter.ts
- frontend/src/components/ApexChart/utils/index.ts
- frontend/src/main.ts
- frontend/src/views/AppView.vue
@tianzhou Please checkout the style.
> feat: add cost line chart

- frontend/seo/matrix.ts
1. cloud provider
2. cloud service
3. database 
4. charge type
5. machine type
> feat: add seo matrix

- frontend/src/components/CheckInstanceSidebar.vue
- frontend/src/components/CostTable/CostTable.vue
- frontend/src/router/index.ts
- frontend/src/stores/dataTableItem.ts
- frontend/src/types/index.ts
- frontend/src/types/route.ts
- frontend/src/views/AppView.vue
- frontend/src/views/CompareView.vue
the URL woule be like:
https://dbcost-pr-70.onrender.com/compare?key=db-N1Highmem-8-52::us-east4::DEC3-E170-9BF7,db.r4.4xlarge::us-east-1::YWYQKBC63RWRKG7Z.JRTCKXETXF,db.r5.4xlarge::us-east-1::ZWXBNQCVVTQSGC4C.JRTCKXETXF
> implement URL sharing for compare page

- frontend/src/components/CostTable/CostTable.vue
> feat: allow to sort on the expected cost

- frontend/src/components/CheckInstanceSidebar.vue
- frontend/src/layout/AppLayout.vue
- frontend/src/views/AppView.vue
> widered the compare side bar & change the shopping cart icon to text

- frontend/src/components/CostTableMenu.vue
- frontend/src/components/CostTableSlider.vue
- frontend/src/views/AppView.vue
> relayout toolbar

- .github/workflows/schedule.yml
- update PR title and commit message
- add more descriptions to the PR body
> chore: update GitHub Actions

- frontend/components/RegionMenu.tsx
https://user-images.githubusercontent.com/56376387/190595420-f5851d2e-6863-4c0d-bdae-72258f5c1ac4.mp4
https://user-images.githubusercontent.com/56376387/190595429-8c61ae7e-3014-4332-ad43-3e65f3459bcc.mp4
> fix: default checked regions disappear

- frontend/components/RegionMenu.tsx
> feat: add provider icons after region names

- frontend/components/Footer.tsx
- frontend/components/Header.tsx
- frontend/layouts/main.tsx
> style: center content on large screens

- frontend/components/Header.tsx
Reference: https://nextjs.org/blog/next-12-2.
> chore: remove redundant anchor tags

- frontend/components/RegionMenu.tsx
Icons get re-rendered.
https://user-images.githubusercontent.com/56376387/195971817-94d289c9-dbe7-497f-8c5f-b1754b99196b.mp4 
Icons don't get re-rendered.
https://user-images.githubusercontent.com/56376387/195971805-a2ee2233-c07b-40df-b013-4f8a9a327b5d.mp4
> perf: reduce region menu icons' re-render

- frontend/.npmrc
- frontend/components/CompareTable.tsx
- frontend/components/LineChart.tsx
- frontend/components/RelatedTable.tsx
- frontend/components/SearchMenu.tsx
- frontend/package.json
- frontend/pages/index.tsx
- frontend/pages/instance/[instance].tsx
- frontend/pages/provider/[provider].tsx
- frontend/pages/region/[region].tsx
- frontend/pnpm-lock.yaml
- frontend/stores/dbInstanceContext.tsx
- frontend/tsconfig.json
- frontend/types/chart.ts
- frontend/types/index.ts
- frontend/types/route.ts
- frontend/types/table.ts
- frontend/utils/index.ts
- frontend/utils/region.ts
> feat: region detail pages

- frontend/types/searchConfig.ts
> chore: only check AWS in the default view

- frontend/components/CompareTable.tsx
> feat: sort expected cost ascending by default

- frontend/components/Header.tsx
- frontend/components/SearchMenu.tsx
- frontend/layouts/main.tsx
https://user-images.githubusercontent.com/56376387/198303782-5e97e93c-9fb0-4cae-9bae-6146ed743fb0.mp4
> style: improve the mobile view

- frontend/components/RelatedTable.tsx
- frontend/pages/instance/[instance].tsx
- frontend/utils/instance.ts
> feat: update related table wording

- frontend/components/ButtonGroup.tsx
https://user-images.githubusercontent.com/87714218/198285151-44d57ada-c011-4490-bf75-8ad759def38d.mp4
> feat: copy url to clipboard

- frontend/components/RelatedTable.tsx
- frontend/pages/instance/[instance].tsx
- frontend/types/table.ts
> feat: include pricing info in related tables

- frontend/components/SearchMenu.tsx
> style: add separators in search config bar and add unit to min ram

- frontend/next-sitemap.config.js
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/public/.gitignore
> feat: generate sitemap

- frontend/components/Header.tsx
> style: improve header layout

- frontend/components/CompareTable.tsx
> feat: retain 3 digits after the decimal point on hourly prices

- frontend/components/CompareBadgeGroup.tsx
- frontend/components/CompareMenu.tsx
- frontend/components/CompareTable.tsx
- frontend/components/LineChart.tsx
- frontend/components/RegionPricingTable.tsx
- frontend/components/SearchMenu.tsx
- frontend/pages/compare/[comparison].tsx
- frontend/pages/index.tsx
- frontend/tailwind.config.js
- frontend/types/route.ts
- frontend/types/searchConfig.ts
- frontend/types/table.ts
- frontend/utils/compare.ts
- frontend/utils/index.ts
> feat: instance comparison page

- frontend/layouts/main.tsx
- frontend/pages/compare/[comparison].tsx
- frontend/pages/index.tsx
- frontend/pages/instance/[instance].tsx
- frontend/pages/provider/[provider].tsx
- frontend/pages/region/[region].tsx
> chore: add description and keywords meta tags

- frontend/components/CompareTable.tsx
> fix: table rowSpan error

- frontend/components/SearchMenu.tsx
- frontend/pages/provider/[provider].tsx
> chore: hide reserved checkbox in gcp page

- frontend/components/ButtonGroup.tsx
- frontend/components/CompareMenu.tsx
- frontend/pages/index.tsx
https://user-images.githubusercontent.com/56376387/206075254-ad6335c0-c866-4a29-8304-c9110f8b1c7f.mp4
> chore: move compare menu to page top

- frontend/components/RegionMenu.tsx
https://user-images.githubusercontent.com/56376387/206383442-8fb19dd0-3a4e-4916-8539-43408cc6fdca.mp4
> feat: checkbox to select all regions

- frontend/pages/compare/[comparison].tsx
Compare between GCP instances' pricing in Virginia, too.
> fix: add virginia code for GCP instances

- frontend/components/ButtonGroup.tsx
- frontend/components/CompareMenu.tsx
- frontend/pages/index.tsx
> style: lift compare menu to be above button group

- frontend/layouts/main.tsx
- frontend/next-sitemap.config.js
To resolve the **Page with redirect** issue from Google Search Console.
> chore: make canonical url to be www.dbcost.com

- frontend/pages/_document.tsx
> chore: add lang attribute
